config/routes.rb
Rails.application.routes.draw do
  
 root 'pages#home'

  get '/home', to: 'pages#home'
  
  resources :recipes do
  	member do
  		post 'like'
  
  	end
  	resources :reviews
  end
  
  resources :chefs, except: [:new, :destroy]
  
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 2, maximum: 25 }
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :require_user, except: [:show]
  
  def show
    @ingredient = Ingredient.find(params[:id])  
    @recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @ingredient = Ingredient.new
  end
  
  def create
     @ingredient = Ingredient.new(ing_params)
    if @ingredient.save
      flash[:success] = "Ingredient was created sucessfully"
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  
   private
  
  def ing_params
    params.require(:ingredient).permit(:name)
  end
  
end

app/views/ingredients/_ingredient.html.erb
<span class="quiet"><%= link_to ingredient.name, ingredient_path(ingredient) %> </span>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: 'Create A New Ingredient' %>
<%= render 'shared/errors', obj: @ingredient %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
      <%= form_for @ingredient do |f|%>
         <%= f.label :name %>
         <%= f.text_field :name %>
        
         <%= f.submit 'Create Ingredient', class:"btn btn-success" %>
      <% end %>   
    </div>
</div> 

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: 'Recipes for : ' + @ingredient.name %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path%>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path%>
  </li>
</ul>

<%= will_paginate @recipes %>

<% @ingredient.recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef size: 100), chef_path(recipe.chef) %>
        <h5>Chef Name : <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    <div class="col-lg-6 well">
     <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
     <p><%= recipe.summary %></p>
     <p>Style: <%= render recipe.styles %></p>
     <p>Ingredients: <%= render recipe.ingredients %></p> 
     <p>
       <span class="quiet">
         <small> created: <%= time_ago_in_words(recipe.created_at) %> ago, </small>
       </span>
       <span class="quiet">
         <small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small>
       </span>
     </p>
    <div class="pull-right">
         <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total%> 
         <% end %> &nbsp&nbsp&nbsp&nbsp
         <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
           <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total%> 
         <% end %>
    </div>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: '250x150', class:'gravatar') if recipe.picture? %>
    </div>
  </div>
  <hr/>
<% end %>

<%= will_paginate @recipes %>