config/routes.rb
Rails.application.routes.draw do
  
 root 'pages#home'

  get '/home', to: 'pages#home'
  
  resources :recipes do
  	member do
  		post 'like'
  
  	end
  	resources :reviews
  end
  
  resources :chefs, except: [:new, :destroy]
  
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Tasty Recipes</h1>
  <h2>Recipes via Ruby on Rails</h2>
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">
      Search and View Recipes as a Guest and Sign Up Later
    </h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class:"btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Sign In To Your Account
    </h3>
    <h2 class="left">
      Add\Update Your Recipes, Create Reviews, Add or Dislike Recipes and more ...
    </h2>
    <p><%= link_to "Login To Your Account", login_path, class:"btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      View the source code yourself
    </h3>
    <h2 class="left">
      The source code is hosted on GitHub, just click to go there
    </h2>
    <p><%= link_to "Browse Source Code", "https://github.com/marb61a/myrecipes", class:"btn btn-warning btn-small" %></p>
  </div>
</div>